using UnityEngine;
using UnityEditor;
using System.IO;

public class InputActionEnumarator
{
    private const string m_actionsFilePath = @"/Scripts/InputActions.cs";
    private const string m_inputManagerPath = @"Assets/Prefabs/Rewired Input Manager.prefab";

    [MenuItem("Custom/Generate Action Enumerators")]
    private static void Init()
    {
        string file = "// This file is automatically generated (See InputActionEnumarator.cs)\npublic static class InputAction\n{\n";

        GameObject obj = PrefabUtility.LoadPrefabContents(m_inputManagerPath);
        if (obj != null)
        {
            if(obj.TryGetComponent(out Rewired.InputManager manager))
            {
                foreach(Rewired.InputAction action in manager.userData.GetActions_Copy())
                {
                    Rewired.InputCategory category = manager.userData.GetActionCategory(action.categoryId);

                    file += $"\tpublic const string {category.name}_{action.name} = \"{action.name}\";\n";
                }
            }

            PrefabUtility.UnloadPrefabContents(obj);
        }

        file += "}";

        string filePath = Application.dataPath + m_actionsFilePath;
        File.WriteAllText(filePath, file);
    }
}