using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;

public class ItemEnumarator
{
    private const string m_itemsPath = @"Assets/Resources/Items";
    private const string m_enumFilePath = @"/Scripts/GameItem.cs";

    [MenuItem("Custom/Generate Item Enumerators")]
    private static void Init()
    {
        string file = "// This file is automatically generated (See ItemEnumerator.cs)\npublic enum GameItem\n{\n";

        string[] guids = AssetDatabase.FindAssets("", new[] { m_itemsPath});
        foreach(string guid in guids)
        {
            string id = AssetDatabase.GUIDToAssetPath(guid);
            int start = id.LastIndexOf("/");
            int end = id.LastIndexOf(".");
            string enumName = id.Substring(start + 1, end - start - 1);
            Regex.Replace(enumName, "[^A-Za-z]", "");
            file += $"\t{enumName},\n";
        }
        file += $"\tTotal,\n";
        file += "}";

        string filePath = Application.dataPath + m_enumFilePath;
        File.WriteAllText(filePath, file);
    }
}