// This file is automatically generated (See InputActionEnumarator.cs)
public static class InputAction
{
	// These two values are non-static due to Nintendo style controls
	public static string Inventory_Select = "Select";
	public static string Inventory_Back = "Back";

	public const string Inventory_MoveX = "MoveX";
	public const string Inventory_MoveY = "MoveY";
	public const string Inventory_Special = "Special";
	public const string Default_DecrementResolution = "DecrementResolution";
	public const string Default_IncrementResolution = "IncrementResolution";
}